### ISSUE TITLE
Name conflict in Debian/Ubuntu repository 

### ISSUE THREAD

**Issue by anantshri** [SUPERAndroidAnalyzer/super#104]
the name of the package is already used by another package already present in Debian and ubuntu repositories.

Refer the image here top information is about our deb file and bottom information is about the existing software in distro.
![super](https://cloud.githubusercontent.com/assets/236843/23025084/a56dccac-f482-11e6-8695-697d1c312e07.jpg)

More References 
https://packages.debian.org/jessie/super
http://packages.ubuntu.com/yakkety/super

Having name conflict results in following issue:
1) If someone add's it to a debian repository (fox example i have added in repo.androidtamer.com) it will not be visible to user, and would be hidden behind a screen.
![tamer](https://cloud.githubusercontent.com/assets/236843/23025234/3de8088a-f483-11e6-963d-dc93e2e93d8d.jpg)
2) As its not visible and workable directly the apt-get install super will not work. 

Suggested solution:
We rename the package to say superandroidanalyzer, which will remove all doubts.

**Comment by Razican** [comment]
Yep, I'll first try to talk to Debian packagers, since the `super` Debian package has not received an update since the end of 2007 (that's almost 10 years without a code change). So hopefully nobody uses `super` (I think that almost everybody nowadays uses `sudo` for that matter) and they decide to remove the old `super` package in favour of this one.

If not, as you said, something like `super-analyzer` or so, to make it a bit smaller and easier to remember would work. I'll try to contact somebody today.

**Comment by Razican** [comment]
After [some replies](https://lists.debian.org/debian-mentors/2017/02/msg00187.html) from the Debian community, seems that we will need to change the package name first, and that we won't be able to get into official repos until we remove `dex2jar` and `jd-cli` dependencies. That's something [we are already working on](https://github.com/SUPERAndroidAnalyzer/dalvik) even though it still needs a lot of work. So, our decision for now will be to release a 0.3.1 version with a new package name, `super-analyzer`, but with the same `super` binary.

We didn't want to wait for 0.4.0 since that's gonna take a long time to develop (we will try to release it without those dependencies), and that way it can be introduced in your repository as soon as we release it.

Will comment back when we have it, but could be this weekend.

**Comment by anantshri** [comment]
specifically for androidtamer i am seperately managing dex2jar and planning on managing jd-cli. Right now we are putting the whole deb as is but ya it would be easier to have dex2jar as dependencies instead of being binary bundled. 

As i can see you are already working on an alternative but let me also point out that even google now recommends using enjarify over dex2jar and https://github.com/google/enjarify is opensource too so you might want to look at that also.

also it looks like 0.3.1 is out, i will be trying to package it over weekend and will ping once its available within androidtamer repositories, Also closing issue as this seems to have fixed the name conflict.

**Comment by Razican** [comment]
Thanks for the tip about `enjarify`. We will probably stick to our dependencies until we can get rid of them, I hope that before summer (except for `apktool`). We will release packages tomorrow, so don't worry about packaging :)
