### ISSUE TITLE
Unable to de-compile Linkedin apk

### ISSUE THREAD

**Issue by pushpeshkarki2016** [SUPERAndroidAnalyzer/super#125]
I am unable to run analysis for linkedin apk

```
C:\super>super com.linkedin.android-4.1.95@APK4Fun.com.apk

Starting analysis of com.linkedin.android-4.1.95@APK4Fun.com.
Error: Application analysis failed
        Caused by: apk decompression failed
        Caused by: error loading apk file
        Caused by: Io Error: other os error
        Caused by: The parameter is incorrect. (os error 87)
If you need more information, try to run the program again with the -v flag.
```

**Comment by Razican** [comment]
Please, let me know if my assumptions are correct: You downloaded the APK file from *apk4fun.com*, the version is 4.1.95, and the package is *com.linkedin.android*. You are ussing Windows, right? Which version? Which version of SUPER?

Could you try to change the name of the apk file to *com.linkedin.android.apk*?

Could be an issue with the `@` in the name of the APK, but in any case seems an error from our side or one of our dependencies.

**Comment by pushpeshkarki2016** [comment]
Hi Razican,
Yes, i have download the the APK file from apk4fun.com, the version is 4.1.95, and the package is *com.linkedin.android*. I am using windows 10 64bit machine and i am using super-analyzer-0.4.1-windows-x86_64 version.

I have tried renaming it, it still giving the same error.

```
C:\super>super com.linkedin.android.apk

Starting analysis of com.linkedin.android.
Error: Application analysis failed
        Caused by: apk decompression failed
        Caused by: error loading apk file
        Caused by: Io Error: other os error
        Caused by: The parameter is incorrect. (os error 87)
If you need more information, try to run the program again with the -v flag.
```

**Comment by pushpeshkarki2016** [comment]
Also just to add that when i try the same on MobSF i am able to do it successfully.

**Comment by Razican** [comment]
We confirm it happens in Linux and Windows with that particular application. The error trace in Linux is the following:

```
Error: Application analysis failed
        Caused by: apk decompresion failed
        Caused by: error loading apk file
        Caused by: Invalid Zip archive: Could not find central directory end
```

Seems that the APK file is not valid, but as you say, it seems that other software can decompress it properly. I tried with the default decompressor in Fedora and it works, and seems that it also works in MobSF as you say.

I will check what is happening with it with some time and post an issue, if needed in the [`zip`](https://github.com/mvdnes/zip-rs) crate repository.

There is also a separate issue with the coloring in Windows terminal that I have reported in #126 and that will be tracked in another issue.

**Comment by pushpeshkarki2016** [comment]
when we doing the 0.5 release seems like this project is not moving for last 10 months

**Comment by Razican** [comment]
Hi,

Sorry for not updating this issue, we didn't forget about it. It's true that the project hasn't been updated so much for the last months. It has received updates the last 10 months, though. You can check the changes for the next version [here][develop_commits]. We develop in the `develop` branch to leave the `master` branch only for stable releases. I didn't have the time to fix this particular issue, though.

Luckily I am now back to work and I expect to release the `0.5.0` version before the end of June (sorry for the delay). You can check the open issues for the `0.5.0` version [here][issues_left]. We might move some of them for the `0.6.0` version, since want to publish the multiple fixes and features that have already been done for the 0.5.0 version. Nevertheless, since we see that this bug is a priority, we will work on it as fast as possible to release it on `0.5.0`.

[develop_commits]: https://github.com/SUPERAndroidAnalyzer/super/commits/develop
[issues_left]: https://github.com/SUPERAndroidAnalyzer/super/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A%22SUPER+0.5.0%22

**Comment by Razican** [comment]
Hi @pushpeshkarki2016, I have good news. I've been checking this with the latest update in the `zip` crate and it seems it's fixed. Please, could you confirm that using the latest development code it's fixed?

To check the development build, you need to install Rust with the instructions in [rustup.rs][rustup]. Then, you can download a zip file with the latest development source code [here][dev-download]. Then, you will need to run the following:
```
cargo run --release -- com.linkedin.android.apk --open
```

Please, let me know if the application gets decompiled properly. There is one known issue though, #158, but the previous error should not appear, and a report should be generated.

[rustup]: https://rustup.rs/
[dev-download]: https://github.com/SUPERAndroidAnalyzer/super/archive/develop.zip

**Comment by Razican** [comment]
I'm closing this as it seems fixed in the latest development code. Please, feel free to re-open it if you find the error again in a development version or after the `0.5.0` version is released.
