### ISSUE TITLE
[Question][Rules]

### ISSUE THREAD

**Issue by AnaNunesFernandes** [SUPERAndroidAnalyzer/super#167]
Hello,
I am using your tool and I installed it trough the released binaries. I am using the most recent. But since you have more branches I would like to now which rules does the latest release follow. 
I was looking to the file rules.json of the master branch and I was assuming that all the problems SUPER can detect were there. But since I've seen the other branches I am no longer sure.

Thanks in advance.

**Comment by Chuky9** [comment]
Hello Ana,

First of all, I would like to thank you for using SUPER! We would be very grateful if you could report to us any issue or propose any feature. As we have not modified detection rules file since previous versions, all branches are up to date. Therefore, it should not be any difference regarding to detection results.

I would recommend to use the last stable version which is allocated in "Master" branch.

Best regards!

**Comment by Patryck95** [comment]
I had the same question.
Thank you for your fast reply.

**Comment by AnaNunesFernandes** [comment]
@Patryck95  you must have forgotten that I was the one that started this issue XD.
Well as my team mate said, thank you for your reply.
