### ISSUE TITLE
Integrate with homebrew?

### ISSUE THREAD

**Issue by commjoen** [SUPERAndroidAnalyzer/super#168]
Hi there,
I am starting a project in which I want to include a bunch of android and ios pentesting tools and distribute them to my mac using Ansible. So I wonder:
- is it possible to have the mac os executable as just a downloadable as part of your release?
- is it possible to make SUPER available through homebrew?

Right now i compiled the executable for mac myself and i am downloading it from my dropbox, but it would be really great if i can get the executable from your releases (And not an installer).

**Comment by Razican** [comment]
Hi @commjoen,

Thank you for the comment. We added the *.pkg* file so that it was easier to install. The package not only contains the executable but also some files required for SUPER to work. Nevertheless, it surely seems much more reasonable to create a way so that users can install it with *Homebrew*.

We do have a lack of knowledge on how to do this, though, and I myself have never used a Mac computer, so that's also an issue. I will try to figure out how to do it. In fact, we already generate packages for Linux distributions automatically for each release and we upload them to GitHub, so maybe we don't need to change the infrastructure so much for this.

I'm adding it to the list of TO-DO's, and will update this issue if there is any news.

**Comment by commjoen** [comment]
Hi @Razican ,
thank you very much! I looked at the /target/release and saw the super.bash(-completion) and the super-analyzer binary. Which other files will I need? When I know which ones, and they're available as a downlaodable tar file, then we can use them to make the app working nicely and register at homebrew (https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md is a nice starting point). Next, we can add homebrew instructions.

Ofcourse, I am very willing to help and test in there. Can we use something like the OWASP slack (https://owasp.herokuapp.com/) to collaborate?

**Comment by Razican** [comment]
Hi @commjoen! sorry for replying so late, I think I missed the notification :/

We have the list of files for the RedHat-based distributions [here][spec]. Some of those files are generated after the build, and some are already there in the repo. Not sure if this is enough information.

[spec]: https://github.com/SUPERAndroidAnalyzer/super/blob/master/rpmbuild/super.spec

**Comment by commjoen** [comment]
Hi @Razican , as I am currently pretty flooded with work, it might take a while before I can start fixing it myself, but i hope to find some time in the near future.

**Comment by Razican** [comment]
Hi @commjoen, I understand, try to do your best, there is no release being prepared for the near future, in any case.

**Comment by commjoen** [comment]
Hi @Razican , I unfortunately don't think I will have time for it. I have scripted around it at https://github.com/xebia/mobilehacktools and never found the time to do it "proper" with Brew integration. Let's close this issue for now.
