### ISSUE TITLE
Remove APKTool dependency

### ISSUE THREAD

**Issue by Razican** [SUPERAndroidAnalyzer/super#20]
We should not require the use of APKTool to decompile the software.

**Comment by Razican** [comment]
We currently only use this for XML reading, so it will be easy to remove once we implement something like [this](https://github.com/xgouchet/AXML/blob/master/library/src/main/java/fr/xgouchet/axml/CompressedXmlParser.java).

**Comment by gnieto** [comment]
Hi!
I've started to work on a decoder on Rust for this kind of files, but I've just saw that you assigned this issue to you. Are you already working on this?
If you are, there's any other issue that you want that I work on?
Thanks!

**Comment by Razican** [comment]
Hmmm I'm working on it, yes, but I would of course appreciate help. I was thinking on doing something similar to `aapt` in Rust, as a library, but seems that it's going to be more difficult than what I thought. What do you think?

**Comment by gnieto** [comment]
@Razican Well, at the moment, what I understood from the issue, the main coupling with apktool is due to the binary XML that are on the APKs.
I've been working on a parser for this kind of files, but it's far for being 'production ready' (I've started this at the beginning of the week). This is what I currently have: https://github.com/gnieto/abxml-rs/tree/develop
The intention is to have a library capable to convert AndroidManifest.xml from the binary form to a valid XML, but if you look at the code, now it's only a bunch of println!

**Comment by Razican** [comment]
@gnieto Well, the thing is that binary XML only works for the Manifest, since the rest of the resources are in a `resources.arsc` file that contains them in an unknown format. I'm trying to reverse-engineer `aapt` from the Android project (you can find the code in the Android repository, it's written in C++).

Since we need all the XML files, I think that an approach like that would be better.

**Comment by gnieto** [comment]
Mmm ok, understood. I didn't know this.

So, if at any moment you want some help with something related with this, let me know!

**Comment by Razican** [comment]
@gnieto We will be in [novemb.rs](http://novemb.rs/) code sprint today and tomorrow, if you want to participate :)

**Comment by gnieto** [comment]
About this issue, I know that you have been working on this, but, as I told you, I started working on a Rust library to decode the APKs.

I've a minimal version working that creates an almost identical XMLs output to APKTool on the APKs I've tried (some of the differences are due to rounding issues with floats).

At the moment I'm working on increasing the testing coverage, stabilizing the API and doing some clean ups on the code, but I think that in a couple of weeks I will be able to test the integration on this project

I'm doing this to learn Rust, so I don't want to "impose" this!

**Comment by Razican** [comment]
Wow, that would be awesome. Is the code open source? This requires in any case a deeper discussion. Could you send me an email to the email in my profile?

**Comment by Razican** [comment]
This is now closed. Thanks to @gnieto for his incredible work on android binary XML parsing.

**Comment by Chuky9** [comment]
@Razican Wtf!! Apktool "al carrer"?
